---
language: python

sudo: true

cache:
  directories:
  - /home/travis/.rvm
  - /home/travis/.cache/pip
  - /home/travis/virtualenv

addons:
  apt:
    packages:
    - python-pip
    - ruby-bundler

# Install ansible
install:
  - bundle install
  - pip install -r requirements.txt

  # Check versions
  - ansible --version
  - ansible-lint --version
  - pip show -v ansible-review
  - rubocop --version

script:
  - make
  - bundle exec kitchen create $INSTANCE || true # A minor schlonk to avoid failure during kitchen build.
  - bundle exec kitchen test $INSTANCE

matrix:
  fast_finish: true
  include:
  - python: 2.7
    env: INSTANCE="apply-debian-9"
  - python: 2.7
    env: INSTANCE="check-debian-9"
